categories:
    path: /categories
    controller: category@index
    methods: [GET]
categories_view:
    path: /categories/{id}
    controller: category@view
    methods: [GET]

# Reader Rotuing
readers_all:
    path: /readers
    controller: reader@index
    methods: [GET]
redears_one:
    path: /readers/{id}
    controller: reader@view
    methods: [GET]

homepage:
    path: /
    controller: default@index
    name: homepage
example:
    path: /example/{name}
    controller: default@example
    name: routing_example #optional
    methods: [GET, POST]
    #options:
    #host:
    #schemes:
    #requirements:
example2:
    path: /example2
    controller: default@example2